name: Ola Mundo
on: push
jobs:
  saudacao:
    runs-on: ubuntu-latest
    steps:
      - name: Dizer ola
        run: echo "Ola, aqui é o José!"
      - name: Dizer Adeus
        run: echo "Tchau! Até a proxima"
      - name: Mostrar Data e hora
        run: date
