name: Ola Mundo
on: workflow_dispatch
jobs:
  Minhas_Tarefas:
    runs-on: ubuntu-latest
    steps:
      - name: Dizer ola
        run: echo "Ola, aqui é o José!"
      - name: Dizer Adeus
        run: echo "Tchau! Até a proxima"
      - name: Mostrar Data e hora
        run: date
      - name: Mostrar quem fez Commit
        run: echo "O commit foi feito por ${{github.actor}}"
      
